version: "3"
services:
  app:
    container_name: mailchimp-proxy-api
    image: mailchimp-proxy-api-image:latest
    environment:
      - PROJECT_TITLE=$PROJECT_TITLE
      - PORT=$PORT
      - DOCKER_PORT=$DOCKER_PORT
      - MAILCHIMP_USER=$MAILCHIMP_USER
      - MAILCHIMP_API_KEY=$MAILCHIMP_API_KEY
      - MAILCHIMP_AUDIENCE_ID=$MAILCHIMP_AUDIENCE_ID
      - FRONTEND_URL=$FRONTEND_URL
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - $PORT:$DOCKER_PORT
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ## With node_modules
    # volumes:
    #  - ./node_modules:/usr/src/tmpapp/node_modules/
